image: ruby:2.4.0

pipelines:
  branches:
    master:
      - step:
          name: Test
          caches:
            - bundler
          script:
            - bundle install --path ./vendor
            - bundle exec rake spec
      - step:
          name: Build
          deployment: production
          caches:
            - bundler
          script:
            - bundle install --path ./vendor
            - bundle exec rake build
      - step:
          name: Check style and docs
          caches:
            - bundler
          script:
            - bundle install --path ./vendor
            - bundle exec rake rubocop
            - bundle exec rake yard
    develop:
      - step:
          name: Test
          deployment: test
          caches:
            - bundler
          script:
            - bundle install --path ./vendor
            - bundle exec rake spec
      - step:
          name: Check style and docs
          deployment: staging
          caches:
            - bundler
          script:
            - bundle exec rake rubocop
            - bundle exec rake yard
    feature/*:
      - step:
          name: Test and check style
          caches:
            - bundler
          script:
            - bundle install --path ./vendor
            - bundle exec rake spec
            - bundle exec rake rubocop

  default:
    - step:
        name: Test and Build
        caches:
          - bundler
        script:
          - bundle install --path ./vendor
          - bundle exec rake spec
          - bundle exec rake build
    - step:
        name: Check style and docs
        caches:
          - bundler
        script:
          - bundle install --path ./vendor
          - bundle exec rake rubocop
          - bundle exec rake yard

definitions:
  caches:
    bundler: ./vendor
