# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.4.0

pipelines:
  default:
    - step:
        name: Test and Build
        caches:
          - bundler
        script:
          - bundle install --path ./vendor
          - bundle exec rake spec
          - bundle exec rake rubocop
          - bundle exec rake yard
          - bundle exec rake build

definitions:
  caches:
    bundler: ./vendor
