# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.4.0

pipelines:
  default:
    - step:
        name: RSpec Tests
        caches:
          - bundler
        script:
          - bundle install
          - bundle exec rake spec
    - parallel:
      - step:
          name: Rubocop
          caches:
            - bundler
          script:
            - bundle install
            - bundle exec rake rubocop
      - step:
          name: YARD Documentation
          caches:
            - bundler
          script:
            - bundle install
            - bundle exec rake yard
    - step:
        name: Build Artifact
        caches:
          - bundler
        script:
          - bundle install
          - bundle exec rake build

definitions:
  caches:
    bundler: ./vendor
